version: "3.2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: marianodim/cryptohold:${VERSION:-dev}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
    ports:
      - "1337:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --method=HEAD localhost/system-status.txt"]
      interval: 20s
      timeout: 10s
      retries: 20
