# pull official node base image
FROM node:16-alpine3.14 as build-stage

WORKDIR /app


ENV PATH /app/node_modules/.bin:$PATH

RUN apk --no-cache add git bash curl openssh

COPY . .

RUN git init
RUN git remote set-url origin git@github.com:Matiasnu/BNBHold.git

RUN npm cache clean --force

RUN yarn install

RUN yarn run build






