version: "3.2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend.ci
    image: marianodim/cryptohold:${VERSION:-dev}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
    ports:
      - "1337:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --method=HEAD localhost/system-status.txt"]
      interval: 20s
      timeout: 10s
      retries: 20

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/tmp/db
      - --accounts=20
      - --mnemonic
      - "myth like bonus scare over problem client lizard pioneer submit female collect"
      - --networkId
      - "5777"
      - --hostname
      - "ganache"
  #      - --debug

  # ENTRYPOINT ["node", "./build/cli.node.js"]
  # ENTRYPOINT ["node", "/app/ganache-core.docker.cli.js"]
  # https://github.com/digitaldonkey/ganache-cli-docker-compose/blob/master/docker-compose.yml

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test.ci
    depends_on:
      - ganache
    environment:
      TRUFFLE_VERSION: "5.3.14"
