# pull official node base image
FROM node:16-alpine3.14 as build-stage

WORKDIR /app

VOLUME /root/.ssh

ENV PATH /app/node_modules/.bin:$PATH

ARG GITHUB_CONFIG_USERNAME
ARG GITHUB_CONFIG_EMAIL

RUN apk --no-cache add git bash curl openssh

COPY . .

RUN git config --global user.name "mariano di maggio"
RUN git config --global user.email "mariano.dim@gmail.com"

RUN git remote -v

RUN git config --list

RUN npm cache clean --force

RUN yarn install

RUN yarn run build






