version: "2.3"

services:
  nginx-service:
    build:
      context: .
      dockerfile: Dockerfile.prod.ci
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
    ports:
      - "1337:80"
  #    TODO resolver el tema del healthcheck ya que no funciona      
  #    healthcheck:
  #      test: ["CMD-SHELL", "wget -q --method=HEAD localhost/system-status.txt"]
  #      interval: 20s
  #      timeout: 10s
  #      retries: 20

  ethereum-local:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "85:8545"
    volumes:
      - ./ganache_data:/ganache_data
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/tmp/db
      - --accounts=20
      - --mnemonic
      - "myth like bonus scare over problem client lizard pioneer submit female collect"
      - --networkId
      - "5777"
      - --hostname
      - "0.0.0.0"
      - --debug
# ENTRYPOINT ["node", "./build/cli.node.js"]
# ENTRYPOINT ["node", "/app/ganache-core.docker.cli.js"]
# https://github.com/digitaldonkey/ganache-cli-docker-compose/blob/master/docker-compose.yml
