name: Entorno CI 'snapshot' vesions

on:
  push:
    # publish image as master=snapshot or on new tag
    # except on document and ci changes
    branches:
      - master
    tags:
      - '*'
#    paths-ignore:
#      - '**.md'
#      - '.github/workflows/*yml'

env:
  # TODO: remember to update version on new tag
  # Si se quiere generar una release
  # LATEST_TAG default snapshot
  LATEST_TAG: v1.0.4
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      
jobs:

  coverage:
    needs: test

    runs-on: [self-hosted, node]

    if: github.event_name != 'schedule'
    steps:
      - name: Checkout repo code for testing
        uses: actions/checkout@v2

      - name: Buildeamos la imagen para coverage
        run: |
          # docker-compose --file docker-compose-coverage.yml build web-coverage
          yarn install

      - name: Evaluamos coverage
        run: |
          # docker run -i bnbhold_web-coverage:latest truffle run coverage
          truffle run coverage


  test:
    
    runs-on: [self-hosted, node]
    
    if: github.event_name != 'schedule'
    steps:
      - name: Checkout repo code for testing
        uses: actions/checkout@v2

      - name: Buildeamos todos las imagenes requeridas
        run: |
          echo 'build'
          # docker-compose --file docker-compose-test.yml build

      - name: Levantamos el entorno de test
        run: |
          echo 'tests'
          # docker-compose --file docker-compose-test.yml up --remove-orphans --exit-code-from tests

      - name: Bajamos el entorno de test
        run: |
          echo 'down'
          # docker-compose --file docker-compose-test.yml down

  
  build:
    needs: coverage

    runs-on: [self-hosted, node]

    if: github.event_name == 'push'
    steps:

      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: Logging into dockerhub
        run: sudo docker login docker.io -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS

#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USER }}
#          password: ${{ secrets.DOCKER_HUB_TOKEN }}        
      
      - name: Build docker images and publish to Dockehub
        run: |
          export VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && export VERSION=$VERSION
          [ "$VERSION" == "master" ] && export VERSION=snapshot

          echo VERSION=$VERSION
          docker-compose -f docker-compose.yml build web
          docker-compose -f docker-compose.yml push web

          # tag and push versions X.X and latest
          if echo "$VERSION" | grep -qE '^\w+\.\w+\.\w+$' && [ "$LATEST_TAG" == "$VERSION" ]; then
              export VERSION="latest"
              echo VERSION=$VERSION
              docker-compose -f docker-compose.yml build web
              docker-compose -f docker-compose.yml push web
          fi

  deploy:
    needs: build
    runs-on: [self-hosted, node]
    if: github.event_name != 'schedule'
    steps:

      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: clean cache
        run: npm cache clean --force

      - name: install packages
        run: yarn install

      - name: Build web
        run: CI='' npm run build --prod --verbose
        
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build 


# docker hub token
# 0be86853-409d-4d9e-9f10-8318dbf1923c
