# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Javascript CI (CD lo manejamos a traves de Netlify)

on:
  push:
    branches: [ v0.1 ]
  pull_request:
    branches: [ v0.1 ]
#  workflow-dispatch: # Allow manual execution  

jobs:

  build:

    runs-on: [self-hosted, linux]

    strategy:
      matrix:
        node-version: [v16.0.0]
    name: Ejecutando sobre Node ${{ matrix.java }}

    steps:
    - name: Checkout repo code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version}}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version}}

#    - uses: mr-smithers-excellent/docker-build-push@v5
#      name: Build & push Docker image
#      with:
#        image: marianodim/cryptohold
#        tags: v1, latest
#        registry: registry-url.io
#        dockerfile: Dockerfile.ci
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}        

#     Estos comandos deben ejecutarse dentro del container
#    - name: Install Packages    
#      run: yarn install --save-dev --loglevel verbose 
    # CI=false es para que no cancele el building si encuentra un warning
#    - name: Build page
#      run: CI=false yarn run build --loglevel verbose

# Comento esta seccion de gh-pages porque no funciona el despliegue, hay un problema cuando se define
# el atributo homepage en el package.json, da un error de formato

#    - name: Deploy to gh-pages
#      uses: peaceiris/actions-gh-pages@v3
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        publish_dir: ./build


