# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Javascript CI/CD

on:
  push:
    branches: [ v0.1 ]
  pull_request:
    branches: [ v0.1 ]

jobs:

  build:

    #runs-on: self-hosted-runner
    runs-on: [self-hosted, linux]

    strategy:
      matrix:
        node-version: [v16.0.0]
    name: Ejecutando sobre Node ${{ matrix.java }}

    steps:
    - name: Checkout repo code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version}}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version}}
    - name: Run command ti change path
      run: cd client
    - name: Install packages
      run: npm install -g --save-dev --loglevel verbose
    - name: Install create-react-app
      run: npm install -g create-react-app
    - name: Build page
      run: npm run build --loglevel verbose

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build



