# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Javascript CI (CD lo manejamos a traves de Netlify)

on:
  push:
    branches: [ v0.1 ]
  pull_request:
    branches: [ v0.1 ]
#  workflow-dispatch: # Allow manual execution  

jobs:

  build:

    runs-on: [self-hosted, linux]

    strategy:
      matrix:
        node-version: [v16.0.0]
    name: Ejecutando sobre Node ${{ matrix.java }}

    steps:
    - name: Checkout repo code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version}}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version}}
        
    - name: Install Packages    
      run: npm install --save-dev --loglevel verbose 

    # CI=false es para que no cancele el building si encuentra un warning
    - name: Build page
      run: CI=false npm run build --loglevel verbose

# Comento esta seccion de gh-pages porque no funciona el despliegue, hay un problema cuando se define
# el atributo homepage en el package.json, da un error de formato

#    - name: Deploy to gh-pages
#      uses: peaceiris/actions-gh-pages@v3
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        publish_dir: ./build


